# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on: [push,pull_request]
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Running all test at once
      run: |
        python3 -m xmlrunner discover tests -o test-reports/report.xml
        echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
  publish-test-report:
    if: always()
    needs: [build]
    name: Publish Test Report
    runs-on: self-hosted
    steps:
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: test-reports/report.xml
